services:
  front_end:
    build: 
      context: ./FrontEnd
    container_name: front_end
    ports: 
      - "3000:8000"
    networks:
      - eunoia_network

  nginx:
    image: nginx:1.25.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - eunoia_network
    depends_on:
      - front_end
      - back_end
      - ai_therapist
      # - security_bot
      - auth_service
      # - data_service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  back_end:
    build:
      context: ./BackEnd
    container_name: back_end
    ports:
      - "3001:8000"
    networks:
      - eunoia_network
    restart: always

  ai_therapist:
    build:
      context: ./TherapistAI
    container_name: ai_therapist
    ports: 
      - "3002:8000"
    networks:
      - eunoia_network
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongo
    restart: always

  # security_bot:
  #   build:
  #     context: ./SecurityAI
  #   container_name: security_bot
  #   ports:
  #     - "3006:8000"
  #   networks:
  #     - eunoia_network
  #   restart: always

  # email_service:
  #   build:
  #     context: ./EmailService
  #   container_name: email_service
  #   ports:
  #     - "3003:8000"
  #   networks:
  #     - eunoia_network
  #   depends_on:
  #     - auth_service
  #   restart: always

  auth_service:
    build:
      context: ./UserAuthService
    container_name: auth_service
    ports:
      - "3004:8000"
    networks:
      - eunoia_network
    environment:
      - NEXTAUTH_KEY=${NEXTAUTH_KEY}
    depends_on:
      - postgres
    restart: always

  # data_service:
  #   build:
  #     context: ./UserDataService
  #   container_name: data_service
  #   ports:
  #     - "3005:8000"
  #   networks:
  #     - eunoia_network
  #   depends_on:
  #     - mongo
  #   restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - eunoia_network
    volumes:
      - mongo_data:/data/db
    restart: always

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - eunoia_network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
  mongo_data:
    driver: local
  postgres_data:
    driver: local

networks:
  eunoia_network:
    driver: bridge